name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [23.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: latest

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn expo export
